### ISSUE TITLE
The key differences between this work and the implementation of alphazero in PGX

### ISSUE THREAD

**Issue by CDM1619** [lowrollr/turbozero#16]
A great work! Can you tell me the key differences between this work and the implementation of alphazero in PGX: https://github.com/sotetsuk/pgx/tree/main/examples/alphazero, and what are the specific advantages and disadvantages? I hope to choose a more efficient implementation as the code foundation, thank you!

**Comment by DuaneNielsen** [comment]
I just came from there...  PGX is using mctx from deepmind.  It's great, but the thing is.. it doesn't implement subtree saving.  This means every iteration, it throws out all the search data from the previous iteration and starts again.  According to https://github.com/google-deepmind/mctx/issues/51 this is intentional, due to the library being focused on MuZero.  If you are implementing a model (as opposed to learning one), then I think subtree saving is something you want to have.  In fact there is a fork of MCTX where it was implemented.   This is one of the reasons I'm giving turbozero a look.

**Comment by lowrollr** [comment]
Apologies for the incredibly late reply...

Yeah the main difference here is this repo implements subtree saving and also includes all the necessary utilities for an AZ training run in one place (MCTS + fast Replay Memory Buffer impl + training loop).

The implementation in pgx with mctx is also great!
